### ISSUE TITLE
Error post upgrade

### ISSUE THREAD

**Issue by hbcoding** [SQbQxeKd3JHD8/simple_ConTeXt#6]
Hi,

After upgrading, I do face the following error on Windows 10.
I would appreciate if you could help on that. At the moment, only context compiling is working, but te auto-completion and the windows pop-ups are not working.
Thanks in advance.

DPI mode: per-monitor v2
startup, version: 3176 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/hbcoding/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/hbcoding/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/hbcoding/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.106229
startup time: 0.153228
first paint time: 0.153228
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin simple_ConTeXt.build_on_save
reloading plugin simple_ConTeXt.citations
reloading plugin simple_ConTeXt.completions
reloading plugin simple_ConTeXt.docs
reloading plugin simple_ConTeXt.exec_context
reloading plugin simple_ConTeXt.exec_wrapper
reloading plugin simple_ConTeXt.file_links
reloading plugin simple_ConTeXt.interface
reloading plugin simple_ConTeXt.references
reloading plugin simple_ConTeXt.run_script
reloading plugin simple_ConTeXt.settings
reloading plugin simple_ConTeXt.show_overlay
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2018-05-16 18:10:11, next run at 2018-05-16 19:10:11 or after
loading dictionary Packages/Language - English/en_US.dic
[simple_ConTeXt] generating interface files (in folder "default") for "None"
Exception in thread Thread-6:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\hbcoding\AppData\Roaming\Sublime Text 3\Installed Packages\simple_ConTeXt.sublime-package\interface.py", line 89, in f
    self.context_paths if do_all else paths, overwrite,
  File "C:\Users\hbcoding\AppData\Roaming\Sublime Text 3\Installed Packages\simple_ConTeXt.sublime-package\interface.py", line 99, in run_aux
    self.run_aux_i(path, overwrite)
  File "C:\Users\hbcoding\AppData\Roaming\Sublime Text 3\Installed Packages\simple_ConTeXt.sublime-package\interface.py", line 112, in run_aux_i
    self.run_aux_iii(path, dir_, slug)
  File "C:\Users\hbcoding\AppData\Roaming\Sublime Text 3\Installed Packages\simple_ConTeXt.sublime-package\interface.py", line 131, in run_aux_iii
    self.run_aux_iv(path, dir_, slug)
  File "C:\Users\hbcoding\AppData\Roaming\Sublime Text 3\Installed Packages\simple_ConTeXt.sublime-package\interface.py", line 155, in run_aux_iv
    start_stop=False,
  File "C:\Users\hbcoding\AppData\Roaming\Sublime Text 3\Installed Packages\simple_ConTeXt.sublime-package\scripts/save.py", line 71, in save
    self.load_commands(modules=modules)
  File "C:\Users\hbcoding\AppData\Roaming\Sublime Text 3\Installed Packages\simple_ConTeXt.sublime-package\scripts/save.py", line 149, in load_commands
    self.load_commands_aux_i()
  File "C:\Users\hbcoding\AppData\Roaming\Sublime Text 3\Installed Packages\simple_ConTeXt.sublime-package\scripts/save.py", line 166, in load_commands_aux_i
    self.do_command(child)
  File "C:\Users\hbcoding\AppData\Roaming\Sublime Text 3\Installed Packages\simple_ConTeXt.sublime-package\scripts/save.py", line 251, in do_command
    self.do_command_aux(text, node)
  File "C:\Users\hbcoding\AppData\Roaming\Sublime Text 3\Installed Packages\simple_ConTeXt.sublime-package\scripts/save.py", line 272, in do_command_aux
    self.do_command_aux_i(self.clean_name(name), node)
  File "C:\Users\hbcoding\AppData\Roaming\Sublime Text 3\Installed Packages\simple_ConTeXt.sublime-package\scripts/save.py", line 301, in do_command_aux_i
    message.format(name, child.attrib, child.tag)
simple_ConTeXt.scripts.save.UnexpectedTagError: unexpected tag, name: "xmldoifatt", attrib: "{}", tag: "{http://www.pragma-ade.com/commands}string"

**Comment by SQbQxeKd3JHD8** [comment]
Hi @hbcoding, I can absolutely help with that! I experienced the exact same issue after updating my ConTeXt minimals recently, and I've been looking into it. To translate the error closer into English, it's complaining that it can't parse the ConTeXt (XML) interface files, because the command `\xmldoifatt` description has as argument `<cd:string/>` (a.k.a `{http://www.pragma-ade.com/commands}string`) which simple ConTeXt doesn't understand. For reference, if you're curious, here's what it's description looks like:

```xml
<cd:command name="xmldoifatt" level="style" category="xml" file="lxml-ini.mkiv">
  <cd:arguments>
    <cd:resolve name="argument-node"/>
    <cd:string/>
    <cd:string/>
    <cd:resolve name="argument-true"/>
  </cd:arguments>
</cd:command>
```

There you can see the offending `<cd:string/>` (two of them in-fact). So, this is the first time (to my knowledge) that such an argument has been used in the interface files, so the parser didn't know to handle it. What I've now done (I'll push a new release with the change shortly) is to add `<cd:string/>` in, and also put in a sensible fallback behaviour so in future the parser can still succeed even if it hits something unexpected like this. (It'll still complain in the terminal though about the issue, rather than silently glossing over it, so it can be fixed up eventually.)

I'll close this issue for now, and get cracking on pushing the new release. Expect to wait a couple of hours from now for me to push it out (I'm playing with some other bits and bobs at the moment, wanna reach a stopping point with them) and also for package control to notice the new release. If the issue persists with the new release, then please re-open and we'll have a look at it.
